This is the second tutorial. In this tutorial, you need to do the following things

1. Download the data from <a href="https://www.dropbox.com/s/y32w0bqq1o1rmsr/Wholesale%20customers%20data.csv?dl=0">here</a> and store it in your computer
2. Find out mean of all the variables except for "Channel" and "Region"
3. Mind out median of all the variables (except for "Channel" and "Region") and calculate the difference between mean and median programmatically.
4. Define a user defined function which can take a data frame having all numeric values and can send out IQR values of all the variables. Test the function on the dataset you have downloaded
5. Find out the function **MinCovDet** within sklearn and using it find out the robust Mahalanobis distance between the point (10000,10000,10000,10000,10000,10000) and the first row of the downloaded dataset after discarding "Channel" and "Region"
6. Run PCA on the 6 numeric variables (except "Channel" and "Region") and decide how many components you would like to retain.
7. As you have already extracted median values of the 6 items, extract robust Mahalanobis distance of each sample from the median (i.e. a datapoint containing the 6 medians). How many outliers can you see?
8. Try to remove the outliers and then run kmeans clustering on the remaining data points. 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
whole_data=pd.read_csv("Wholesale_customers_data.csv")

In [2]:
whole_data.head()

Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

In [3]:
from sklearn.covariance import MinCovDet
mu= np.array([10000,10000,10000,10000,10000,10000])

In [18]:
mn=whole_data.drop(['Channel','Region'], axis=1).apply(lambda x: x.mean())
XX=np.array(whole_data.drop(['Channel','Region'], axis=1).iloc[0,:])

In [19]:
yy=XX-mu

In [6]:
cov_robust=MinCovDet()
cov_robust.fit(whole_data.drop(['Channel','Region'],axis=1))

MinCovDet(assume_centered=False, random_state=None, store_precision=True,
     support_fraction=None)

In [7]:
cov_robust.covariance_

array([[ 93228210.7824766 ,  -1872497.43744017,  -3222679.76495318,
          4093607.57827263,  -2781255.44965661,   1666163.19096774],
       [ -1872497.43744017,   5904825.14431842,   6213626.01842872,
          -474531.62576483,   2660317.40406868,    759172.21419355],
       [ -3222679.76495318,   6213626.01842872,  12489534.43797086,
         -1628307.71783559,   4886113.8428616 ,    900964.05677419],
       [  4093607.57827263,   -474531.62576483,  -1628307.71783559,
          5934858.45893861,   -877512.95165453,    142759.71741935],
       [ -2781255.44965661,   2660317.40406868,   4886113.8428616 ,
          -877512.95165453,   2588521.69270552,    246343.36645161],
       [  1666163.19096774,    759172.21419355,    900964.05677419,
           142759.71741935,    246343.36645161,    607622.94967742]])

In [12]:
cov_robust.location_

array([ 11274.55483871,   3165.77096774,   4432.39032258,   2441.69032258,
         1294.22903226,   1012.4       ])

In [21]:
yy

array([ 2669,  -344, -2439, -9786, -7326, -8662], dtype=int64)

In [22]:
sigma_robust = cov_robust.covariance_
S_inv= np.linalg.inv(sigma_robust)
np.dot(np.dot(yy,S_inv),yy)

289.39475450921339

In [25]:
import scipy
scipy.spatial.distance.mahalanobis(XX,mu,S_inv)

289.39475450921344

In [26]:
mcd=MinCovDet()

In [28]:
mcd.fit(whole_data.drop(['Channel','Region'],axis=1))

MinCovDet(assume_centered=False, random_state=None, store_precision=True,
     support_fraction=None)

In [ ]:
mcd.raw_covariance_